import 'server-only';
import { Resend } from 'resend';
import { createServiceRoleClient } from '@/lib/supabase/service-role';

// Lazy singleton, not created at module load. Creating this at the top of
// the file means `new Resend(process.env.RESEND_API_KEY!)` runs the instant
// anything imports this module — including during Next's build-time
// "Collecting page data" step, before env vars are guaranteed to be in
// play. A missing/empty key there takes the whole build down, even for
// pages that never actually send an email. Lazy init means a missing key
// only breaks the one feature that needs it, at the moment it's needed.
let resendClient: Resend | null = null;
function getResendClient(): Resend {
  if (!resendClient) {
    resendClient = new Resend(process.env.RESEND_API_KEY);
  }
  return resendClient;
}

type SendEmailArgs = {
  studioId: string;
  triggerKey: string;
  toEmail: string;
  data: Record<string, string>;
  relatedIds?: Partial<{
    client_id: string; inquiry_id: string; quote_id: string; contract_id: string;
    invoice_id: string; booking_id: string; project_id: string;
  }>;
  /**
   * Skips template lookup/interpolation entirely and sends this HTML as-is.
   * For emails whose content is generated by a dedicated builder function
   * (loops over arrays, conditional sections) rather than a flat {{var}}
   * template — see lib/email/session-vision-template.ts for the first one.
   * Still goes through the same email_logs write as every other email.
   */
  rawHtml?: string;
  rawSubject?: string;
};

/**
 * Every email in the system goes through this function. It always writes
 * an email_logs row, success or failure, so /admin/email-logs is a true
 * record rather than something maintained by hand at each call site.
 *
 * Template resolution: looks for an active email_templates row matching
 * (studio_id, trigger_key). If none exists yet (a studio hasn't customized
 * that email), falls back to a plain default subject/body built from data,
 * so the system never silently fails to send just because a template row
 * is missing. Seed data populates the required triggers — see
 * supabase/seed/run.ts — but this fallback is the safety net for any
 * trigger that's added later without a matching seed row.
 */
export async function sendTransactionalEmail(args: SendEmailArgs) {
  const supabase = createServiceRoleClient();

  let subject: string;
  let body: string;

  if (args.rawHtml) {
    subject = args.rawSubject ?? defaultSubject(args.triggerKey);
    body = args.rawHtml;
  } else {
    const { data: template } = await supabase
      .from('email_templates')
      .select('subject, body')
      .eq('studio_id', args.studioId)
      .eq('trigger_key', args.triggerKey)
      .eq('active', true)
      .maybeSingle();

    subject = template ? interpolate(template.subject, args.data) : defaultSubject(args.triggerKey);
    body = template ? interpolate(template.body, args.data) : defaultBody(args.triggerKey, args.data);
  }

  let resendMessageId: string | null = null;
  let status: 'sent' | 'failed' = 'sent';
  let errorMessage: string | null = null;

  try {
    const result = await getResendClient().emails.send({
      from: process.env.RESEND_FROM_EMAIL!,
      to: args.toEmail,
      subject,
      html: body,
    });
    resendMessageId = result.data?.id ?? null;
  } catch (err) {
    status = 'failed';
    errorMessage = err instanceof Error ? err.message : 'Unknown error sending email';
  }

  await supabase.from('email_logs').insert({
    studio_id: args.studioId,
    client_id: args.relatedIds?.client_id ?? null,
    inquiry_id: args.relatedIds?.inquiry_id ?? null,
    quote_id: args.relatedIds?.quote_id ?? null,
    contract_id: args.relatedIds?.contract_id ?? null,
    invoice_id: args.relatedIds?.invoice_id ?? null,
    booking_id: args.relatedIds?.booking_id ?? null,
    project_id: args.relatedIds?.project_id ?? null,
    resend_message_id: resendMessageId,
    to_email: args.toEmail,
    subject,
    status,
    error_message: errorMessage,
  });

  return { sent: status === 'sent', error: errorMessage };
}

function interpolate(template: string, data: Record<string, string>): string {
  return template.replace(/\{\{(\w+)\}\}/g, (_, key) => data[key] ?? '');
}

function defaultSubject(triggerKey: string): string {
  const subjects: Record<string, string> = {
    inquiry_received: 'New inquiry received',
    quote_sent: 'Your session quote is ready',
    quote_accepted: 'Quote accepted',
    contract_sent: 'Please review and sign your contract',
    contract_signed: 'Contract signed',
    invoice_sent: 'Your invoice is ready',
    payment_received: 'Payment received',
    not_yet_booked_reminder: 'Your session is not booked yet',
    scheduling_link: "You're ready to pick your session date",
    booking_confirmation: 'Your session is booked',
    portal_setup: 'Your session portal is ready',
  };
  return subjects[triggerKey] ?? 'An update on your session';
}

function defaultBody(triggerKey: string, data: Record<string, string>): string {
  if (triggerKey === 'not_yet_booked_reminder') {
    return `<p>Hi ${data.firstName ?? ''},</p>
      <p>Your date isn't secured yet. Please sign your contract and pay your invoice to lock in your session.
      Once that's done, you'll receive the scheduling link to choose your date and time.</p>
      <p>Reach out any time if you have questions, we're here.</p>`;
  }
  if (triggerKey === 'scheduling_link') {
    return `<p>Hi ${data.firstName ?? ''},</p>
      <p>You're all set, contract signed and invoice paid. Pick your session date and time here:</p>
      <p><a href="${data.schedulingUrl}">${data.schedulingUrl}</a></p>`;
  }
  if (triggerKey === 'portal_setup') {
    return `<p>Hi ${data.firstName ?? ''},</p>
      <p>Your session portal is ready. Inside you'll find your session details, inspiration, notes, documents,
      location, weather, and a direct place to send ideas to our creative team.</p>
      <p><a href="${data.portalUrl}">${data.portalUrl}</a></p>
      <p>Come back anytime as we prepare for your session.</p>`;
  }
  return `<p>Hi ${data.firstName ?? ''},</p><p>There's an update on your session. Reach out if you have questions.</p>`;
}
